### ISSUE TITLE
cylon-firmata fails to automatically install when new Cylon project is created (with latest version of Node)

### ISSUE THREAD

**Issue by munyirik** [ms-iot/ntvsiot#53]
The error logs are below. The workaround for this bug is to:
1. Open package.json.
2. Press save (the second npm install command works).

npm WARN engine cylon@1.1.0: wanted: {"node":">= 0.10.20"} (current: {"node":"5.0.0-0","npm":"3.3.6"})
npm WARN engine serialport@2.0.2: wanted: {"node":">= 0.10.0"} (current: {"node":"5.0.0-0","npm":"3.3.6"})
npm WARN engine sf@0.1.7: wanted: {"node":">=0.6.0"} (current: {"node":"5.0.0-0","npm":"3.3.6"})
npm WARN engine wordwrap@0.0.3: wanted: {"node":">=0.4.0"} (current: {"node":"5.0.0-0","npm":"3.3.6"})
> serialport@2.0.2 install C:\Projects\CylonUwp9\node_modules\serialport
> node-pre-gyp install --fallback-to-build
C:\Projects\CylonUwp9\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs (chakra next)\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean ) 
C:\Projects\CylonUwp9\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs (chakra next)\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32\serialport.node --module_name=serialport --module_path=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32 )  else (node  configure --fallback-to-build --module=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32\serialport.node --module_name=serialport --module_path=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32 ) 
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 404 response downloading https://nodejs.org/dist/v5.0.0-0/node-v5.0.0-0-headers.tar.gz
gyp ERR! stack    at Anonymous function (C:\Program Files (x86)\nodejs (chakra next)\node_modules\npm\node_modules\node-gyp\lib\install.js:244:11)
gyp ERR! stack    at emitOne (events.js:82:7)
gyp ERR! stack    at emit (events.js:169:7)
gyp ERR! stack    at Request.prototype.onRequestResponse (C:\Program Files (x86)\nodejs (chakra next)\node_modules\npm\node_modules\request\request.js:998:5)
gyp ERR! stack    at emitOne (events.js:77:5)
gyp ERR! stack    at emit (events.js:169:7)
gyp ERR! stack    at parserOnIncomingClient (_http_client.js:418:3)
gyp ERR! stack    at parserOnHeadersComplete (_http_common.js:88:5)
gyp ERR! stack    at socketOnData (_http_client.js:308:3)
gyp ERR! stack    at emitOne (events.js:77:5)
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32\serialport.node --module_name=serialport --module_path=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32' (1)
gyp ERR! stack    at emit (events.js:169:7)
gyp ERR! stack    at readableAddChunk (_stream_readable.js:146:9)
gyp ERR! stack    at Readable.prototype.push (_stream_readable.js:110:3)
gyp ERR! stack    at onread (net.js:523:5)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files (x86)\\nodejs (chakra next)\\node.exe" "C:\\Program Files (x86)\\nodejs (chakra next)\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Projects\\CylonUwp9\\node_modules\\serialport\\build\\serialport\\v2.0.2\\Release\\node-v46-win32-ia32\\serialport.node" "--module_name=serialport" "--module_path=C:\\Projects\\CylonUwp9\\node_modules\\serialport\\build\\serialport\\v2.0.2\\Release\\node-v46-win32-ia32"
gyp ERR! cwd C:\Projects\CylonUwp9\node_modules\serialport
gyp ERR! node -v v5.0.0-0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32\serialport.node --module_name=serialport --module_path=C:\Projects\CylonUwp9\node_modules\serialport\build\serialport\v2.0.2\Release\node-v46-win32-ia32' (1)
node-pre-gyp ERR! stack    at Anonymous function (C:\Projects\CylonUwp9\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:13)
node-pre-gyp ERR! stack    at emitTwo (events.js:87:5)
node-pre-gyp ERR! stack    at emit (events.js:172:7)
node-pre-gyp ERR! stack    at maybeClose (internal/child_process.js:818:5)
node-pre-gyp ERR! stack    at _handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10240
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs (chakra next)\\node.exe" "C:\\Projects\\CylonUwp9\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Projects\CylonUwp9\node_modules\serialport
node-pre-gyp ERR! node -v v5.0.0-0
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok 
CylonUwp9@0.0.0 C:\Projects\CylonUwp9
npm ERR! Windows_NT 10.0.10240
├── browser-serialport@2.0.3  extraneous
npm ERR! argv "C:\\Program Files (x86)\\nodejs (chakra next)\\node.exe" "C:\\Program Files (x86)\\nodejs (chakra next)\\node_modules\\npm\\bin\\npm-cli.js" "install"
├── cylon@1.1.0 
npm ERR! node v5.0.0-0
├── cylon-gpio@0.26.0 
npm ERR! npm  v3.3.6
├── cylon-i2c@0.22.0 
npm ERR! code ELIFECYCLE
└── es6-shim@0.33.8  extraneous
npm ERR! serialport@2.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@2.0.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\CylonUwp9\npm-debug.log

**Comment by munyirik** [comment]
Fix in next release. The problem is with addon.gypi where path to node.lib in the sdk (that's installed with Node.js Chakra) isn't set correctly.
